var skills = [  
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20654,
         "skill":{  
            "id":196,
            "skillId":196,
            "skillName":"Toplink",
            "skillGroupName":"Design und Programmierung",
            "description":"Toplink"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20655,
         "skill":{  
            "id":199,
            "skillId":199,
            "skillName":"WebServices",
            "skillGroupName":"Design und Programmierung",
            "description":"WebServies"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20652,
         "skill":{  
            "id":189,
            "skillId":189,
            "skillName":"Shell Script",
            "skillGroupName":"Design und Programmierung",
            "description":"Shell Script"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20653,
         "skill":{  
            "id":194,
            "skillId":194,
            "skillName":"SWING",
            "skillGroupName":"Design und Programmierung",
            "description":"SWING"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20650,
         "skill":{  
            "id":187,
            "skillId":187,
            "skillName":"SAX",
            "skillGroupName":"Design und Programmierung",
            "description":"SAX"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20651,
         "skill":{  
            "id":188,
            "skillId":188,
            "skillName":"Servlets",
            "skillGroupName":"Design und Programmierung",
            "description":"Servlets"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20648,
         "skill":{  
            "id":85,
            "skillId":85,
            "skillName":"Maven",
            "skillGroupName":"Design und Programmierung",
            "description":"Maven"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20649,
         "skill":{  
            "id":185,
            "skillId":185,
            "skillName":"REST",
            "skillGroupName":"Design und Programmierung",
            "description":"REST"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20646,
         "skill":{  
            "id":325,
            "skillId":325,
            "skillName":"jQuery",
            "skillGroupName":"Design und Programmierung",
            "description":null
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20647,
         "skill":{  
            "id":403,
            "skillId":403,
            "skillName":"JSON",
            "skillGroupName":"Design und Programmierung",
            "description":null
         },
         "rating":"EXPERT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"EXPERT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20644,
         "skill":{  
            "id":170,
            "skillId":170,
            "skillName":"Java EE",
            "skillGroupName":"Design und Programmierung",
            "description":"Java EE"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20645,
         "skill":{  
            "id":165,
            "skillId":165,
            "skillName":"JAXB",
            "skillGroupName":"Design und Programmierung",
            "description":"JAXB"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20642,
         "skill":{  
            "id":150,
            "skillId":150,
            "skillName":"C",
            "skillGroupName":"Design und Programmierung",
            "description":"C"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20643,
         "skill":{  
            "id":158,
            "skillId":158,
            "skillName":"EJB",
            "skillGroupName":"Design und Programmierung",
            "description":"EJB"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20640,
         "skill":{  
            "id":390,
            "skillId":390,
            "skillName":"Android Development",
            "skillGroupName":"Design und Programmierung",
            "description":null
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20641,
         "skill":{  
            "id":151,
            "skillId":151,
            "skillName":"CORBA",
            "skillGroupName":"Design und Programmierung",
            "description":"CORBA"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20671,
         "skill":{  
            "id":346,
            "skillId":346,
            "skillName":"LDAP",
            "skillGroupName":"Netzwerke, Dienste und Monitoring",
            "description":null
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20670,
         "skill":{  
            "id":118,
            "skillId":118,
            "skillName":"Nagios",
            "skillGroupName":"Monitoring",
            "description":"Nagios"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20669,
         "skill":{  
            "id":348,
            "skillId":348,
            "skillName":"Problem Management",
            "skillGroupName":"Methoden und Vorgehensmodelle",
            "description":"Problem Management z.B. nich ITIL"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20668,
         "skill":{  
            "id":134,
            "skillId":134,
            "skillName":"ITIL",
            "skillGroupName":"Methoden und Vorgehensmodelle",
            "description":"ITIL"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20667,
         "skill":{  
            "id":349,
            "skillId":349,
            "skillName":"Incident Management",
            "skillGroupName":"Methoden und Vorgehensmodelle",
            "description":null
         },
         "rating":"THEORETICAL",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"THEORETICAL",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20666,
         "skill":{  
            "id":129,
            "skillId":129,
            "skillName":"Change Management",
            "skillGroupName":"Methoden und Vorgehensmodelle",
            "description":"Change Management"
         },
         "rating":"THEORETICAL",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"THEORETICAL",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20665,
         "skill":{  
            "id":301,
            "skillId":301,
            "skillName":"Anforderungsanalyse",
            "skillGroupName":"Methoden und Vorgehensmodelle",
            "description":"Anforderungsanalyse"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20664,
         "skill":{  
            "id":375,
            "skillId":375,
            "skillName":"Agiles Requirements Engineering (SCRUM)",
            "skillGroupName":"Methoden und Vorgehensmodelle",
            "description":"Agile Anforderungsermittlung / Anforderungsermittlung in SCRUM-Projekten"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20663,
         "skill":{  
            "id":307,
            "skillId":307,
            "skillName":"Agile Methoden (SCRUM)",
            "skillGroupName":"Methoden und Vorgehensmodelle",
            "description":"Agile Methoden (SCRUM)"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20662,
         "skill":{  
            "id":382,
            "skillId":382,
            "skillName":"Wicket",
            "skillGroupName":"Frontendtechnologien",
            "description":null
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20661,
         "skill":{  
            "id":337,
            "skillId":337,
            "skillName":"Vaadin",
            "skillGroupName":"Frontendtechnologien",
            "description":null
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20660,
         "skill":{  
            "id":176,
            "skillId":176,
            "skillName":"JSP",
            "skillGroupName":"Frontendtechnologien",
            "description":"JSP"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20659,
         "skill":{  
            "id":387,
            "skillId":387,
            "skillName":"HTML 5",
            "skillGroupName":"Frontendtechnologien",
            "description":null
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20658,
         "skill":{  
            "id":338,
            "skillId":338,
            "skillName":"GWT",
            "skillGroupName":"Frontendtechnologien",
            "description":"Google Web Toolkit"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20657,
         "skill":{  
            "id":384,
            "skillId":384,
            "skillName":"Angular JS",
            "skillGroupName":"Frontendtechnologien",
            "description":null
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20656,
         "skill":{  
            "id":202,
            "skillId":202,
            "skillName":"XSD",
            "skillGroupName":"Design und Programmierung",
            "description":"XSD"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20637,
         "skill":{  
            "id":40,
            "skillId":40,
            "skillName":"Touristik",
            "skillGroupName":"Branchen",
            "description":"Touristik"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20636,
         "skill":{  
            "id":19,
            "skillId":19,
            "skillName":"AIX",
            "skillGroupName":"Betriebssysteme",
            "description":"AIX"
         },
         "rating":"THEORETICAL",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"THEORETICAL",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20639,
         "skill":{  
            "id":146,
            "skillId":146,
            "skillName":"Ajax",
            "skillGroupName":"Design und Programmierung",
            "description":"Ajax"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20638,
         "skill":{  
            "id":48,
            "skillId":48,
            "skillName":"PostgreSQL",
            "skillGroupName":"Datenbanken und Datentechnologien",
            "description":"PostgreSQL"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20633,
         "skill":{  
            "id":25,
            "skillId":25,
            "skillName":"UNIX",
            "skillGroupName":"Betriebssysteme",
            "description":"UNIX"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20632,
         "skill":{  
            "id":23,
            "skillId":23,
            "skillName":"Mac OS X",
            "skillGroupName":"Betriebssysteme",
            "description":"Mac OS"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20635,
         "skill":{  
            "id":392,
            "skillId":392,
            "skillName":"iOS",
            "skillGroupName":"Betriebssysteme",
            "description":"iPhone Betriebssystem"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20634,
         "skill":{  
            "id":21,
            "skillId":21,
            "skillName":"FreeBSD",
            "skillGroupName":"Betriebssysteme",
            "description":"FreeBSD"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20631,
         "skill":{  
            "id":24,
            "skillId":24,
            "skillName":"Solaris",
            "skillGroupName":"Betriebssysteme",
            "description":"Solaris"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20630,
         "skill":{  
            "id":393,
            "skillId":393,
            "skillName":"Android",
            "skillGroupName":"Betriebssysteme",
            "description":"Android / Google mobiles Betriebssystem"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":22150,
         "skill":{  
            "id":434,
            "skillId":434,
            "skillName":"Ausbilder (IHK)",
            "skillGroupName":"Zertifizierungen",
            "description":"Ausbilder (IHK)"
         },
         "rating":"EXPERT",
         "lastUpdatedDate":1400025600000
      },
      "originalSkillValue":"EXPERT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":22151,
         "skill":{  
            "id":428,
            "skillId":428,
            "skillName":"MongoDB for Java Developers ",
            "skillGroupName":"Zertifizierungen",
            "description":"MongoDB for Java Developers "
         },
         "rating":"EXPERT",
         "lastUpdatedDate":1400025600000
      },
      "originalSkillValue":"EXPERT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28492,
         "skill":{  
            "id":131,
            "skillId":131,
            "skillName":"Definition und Koordination von Entwicklungsanforderungen",
            "skillGroupName":"Sonstiges",
            "description":"Definition und Koordination von Entwicklungsanforderungen"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20680,
         "skill":{  
            "id":214,
            "skillId":214,
            "skillName":"MS Project",
            "skillGroupName":"Projektorganisationstools",
            "description":"MS Project"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28493,
         "skill":{  
            "id":219,
            "skillId":219,
            "skillName":"Erfahrung in internationalen Projekten",
            "skillGroupName":"Sonstiges",
            "description":"Erfahrung in internationalen Projekten"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20681,
         "skill":{  
            "id":215,
            "skillId":215,
            "skillName":"MS Visio",
            "skillGroupName":"Projektorganisationstools",
            "description":"MS Visio"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28494,
         "skill":{  
            "id":268,
            "skillId":268,
            "skillName":"Erstellen fachlicher und technischer Datenmodelle",
            "skillGroupName":"Sonstiges",
            "description":"Erstellen fachlicher und technischer Datenmodelle"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20682,
         "skill":{  
            "id":216,
            "skillId":216,
            "skillName":"xProcess",
            "skillGroupName":"Projektorganisationstools",
            "description":"xProcess"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28495,
         "skill":{  
            "id":269,
            "skillId":269,
            "skillName":"Erstellen von Fachkonzepten, DV-Konzepten",
            "skillGroupName":"Sonstiges",
            "description":"Erstellen von Fachkonzepten, DV-Konzepten"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20683,
         "skill":{  
            "id":104,
            "skillId":104,
            "skillName":"StarOffice",
            "skillGroupName":"Projektorganisationstools",
            "description":"StarOffice"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28488,
         "skill":{  
            "id":206,
            "skillId":206,
            "skillName":"Atlassian Confluence",
            "skillGroupName":"Projektorganisationstools",
            "description":"Atlassian Confluence"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20684,
         "skill":{  
            "id":249,
            "skillId":249,
            "skillName":"Aufbau und Betrieb VPN-Infrastruktur",
            "skillGroupName":"Security",
            "description":"Aufbau und Betrieb VPN-Infrastruktur"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28489,
         "skill":{  
            "id":213,
            "skillId":213,
            "skillName":"MS Office",
            "skillGroupName":"Projektorganisationstools",
            "description":"MS Office"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20685,
         "skill":{  
            "id":246,
            "skillId":246,
            "skillName":"Client-Zertifikate",
            "skillGroupName":"Security",
            "description":"Client-Zertifikate"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28490,
         "skill":{  
            "id":252,
            "skillId":252,
            "skillName":"Apache Tomcat",
            "skillGroupName":"Servertechnologien",
            "description":"Apache Tomcat"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20686,
         "skill":{  
            "id":125,
            "skillId":125,
            "skillName":"OpenSSL",
            "skillGroupName":"Security",
            "description":"OpenSSL"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28491,
         "skill":{  
            "id":264,
            "skillId":264,
            "skillName":"Backendentwicklung auf Basis Java EE",
            "skillGroupName":"Sonstiges",
            "description":"Backendentwicklung auf Basis Java EE"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20687,
         "skill":{  
            "id":247,
            "skillId":247,
            "skillName":"PGP",
            "skillGroupName":"Security",
            "description":"PGP"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28484,
         "skill":{  
            "id":324,
            "skillId":324,
            "skillName":"JavaScript",
            "skillGroupName":"Design und Programmierung",
            "description":null
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20672,
         "skill":{  
            "id":121,
            "skillId":121,
            "skillName":"HTTP",
            "skillGroupName":"Netzwerke, Dienste und Monitoring",
            "description":"HTTP"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28485,
         "skill":{  
            "id":340,
            "skillId":340,
            "skillName":"MQ Series",
            "skillGroupName":"Design und Programmierung",
            "description":null
         },
         "rating":"BASIC",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20673,
         "skill":{  
            "id":120,
            "skillId":120,
            "skillName":"DNS Server",
            "skillGroupName":"Netzwerke, Dienste und Monitoring",
            "description":"DNS Server"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28486,
         "skill":{  
            "id":186,
            "skillId":186,
            "skillName":"RMI",
            "skillGroupName":"Design und Programmierung",
            "description":"RMI"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20674,
         "skill":{  
            "id":124,
            "skillId":124,
            "skillName":"Mail Server",
            "skillGroupName":"Netzwerke, Dienste und Monitoring",
            "description":"Mail Server"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28487,
         "skill":{  
            "id":122,
            "skillId":122,
            "skillName":"HTTPS",
            "skillGroupName":"Netzwerke, Dienste und Monitoring",
            "description":"HTTPS"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20675,
         "skill":{  
            "id":126,
            "skillId":126,
            "skillName":"Routing /Switching",
            "skillGroupName":"Netzwerke, Dienste und Monitoring",
            "description":"Routing /Switching"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28480,
         "skill":{  
            "id":416,
            "skillId":416,
            "skillName":"Oracle Certified Professional, Java SE 6 Programmer ",
            "skillGroupName":"Zertifizierungen",
            "description":"Oracle Certified Professional, Java SE 6 Programmer \n"
         },
         "rating":"EXPERT",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"EXPERT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20676,
         "skill":{  
            "id":405,
            "skillId":405,
            "skillName":"Virtual Box",
            "skillGroupName":"Netzwerke, Dienste und Monitoring",
            "description":"Virtual Box"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28481,
         "skill":{  
            "id":41,
            "skillId":41,
            "skillName":"DB2",
            "skillGroupName":"Datenbanken und Datentechnologien",
            "description":"DB2"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20677,
         "skill":{  
            "id":210,
            "skillId":210,
            "skillName":"Atlassian JIRA",
            "skillGroupName":"Projektorganisationstools",
            "description":"Atlassian JIRA"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28482,
         "skill":{  
            "id":371,
            "skillId":371,
            "skillName":"MongoDB",
            "skillGroupName":"Datenbanken und Datentechnologien",
            "description":null
         },
         "rating":"BASIC",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20678,
         "skill":{  
            "id":205,
            "skillId":205,
            "skillName":"Bugzilla",
            "skillGroupName":"Projektorganisationstools",
            "description":"Bugzilla"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28483,
         "skill":{  
            "id":161,
            "skillId":161,
            "skillName":"Hibernate",
            "skillGroupName":"Design und Programmierung",
            "description":"Hibernate"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20679,
         "skill":{  
            "id":207,
            "skillId":207,
            "skillName":"Edgewall Trac",
            "skillGroupName":"Projektorganisationstools",
            "description":"Edgewall Trac"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20697,
         "skill":{  
            "id":69,
            "skillId":69,
            "skillName":"CruiseControl",
            "skillGroupName":"Tools",
            "description":"CruiseControl"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20696,
         "skill":{  
            "id":332,
            "skillId":332,
            "skillName":"Checkstyle",
            "skillGroupName":"Tools",
            "description":null
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20699,
         "skill":{  
            "id":82,
            "skillId":82,
            "skillName":"Java Web Start",
            "skillGroupName":"Tools",
            "description":"Java Web Start"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20698,
         "skill":{  
            "id":71,
            "skillId":71,
            "skillName":"CVS",
            "skillGroupName":"Tools",
            "description":"CVS"
         },
         "rating":"THEORETICAL",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"THEORETICAL",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28505,
         "skill":{  
            "id":106,
            "skillId":106,
            "skillName":"Spring",
            "skillGroupName":"Tools",
            "description":"Spring"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20701,
         "skill":{  
            "id":341,
            "skillId":341,
            "skillName":"MQ Series",
            "skillGroupName":"Tools",
            "description":null
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28504,
         "skill":{  
            "id":377,
            "skillId":377,
            "skillName":"Liferay Developer Studio",
            "skillGroupName":"Tools",
            "description":null
         },
         "rating":"BASIC",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20700,
         "skill":{  
            "id":322,
            "skillId":322,
            "skillName":"Jenkins",
            "skillGroupName":"Tools",
            "description":null
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28507,
         "skill":{  
            "id":334,
            "skillId":334,
            "skillName":"TDD",
            "skillGroupName":"Tools",
            "description":"Test driven development"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20703,
         "skill":{  
            "id":366,
            "skillId":366,
            "skillName":"XCode",
            "skillGroupName":"Tools",
            "description":"Xcode ist eine integrierte Entwicklungsumgebung von Apple, mit der man Programme für Mac OS X und iOS schreiben kann. Es ist nur für Mac OS X verfügbar. Xcode ist hauptsächlich für die Programmiersprachen C, C++ und Objective-C mit dem Cocoa-Framework gedacht, durch seine Modularität kann man damit aber auch Programme in anderen Sprachen schreiben (etwa in Java, Ruby, Perl oder Pascal).\nDie Anwendung Xcode ist Bestandteil des gleichnamigen Software-Entwicklungspakets. Zur besseren Unterscheidung wird die Anwendung von Apple „Xcode IDE“ und das gesamte Entwicklungspaket meist „Xcode Tools“ (seltener „Xcode Package“) genannt."
         },
         "rating":"THEORETICAL",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"THEORETICAL",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28506,
         "skill":{  
            "id":107,
            "skillId":107,
            "skillName":"SVN",
            "skillGroupName":"Tools",
            "description":"SVN"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20702,
         "skill":{  
            "id":91,
            "skillId":91,
            "skillName":"Netbeans",
            "skillGroupName":"Tools",
            "description":"Netbeans"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28501,
         "skill":{  
            "id":287,
            "skillId":287,
            "skillName":"Web- und Frontendtechnologien",
            "skillGroupName":"Sonstiges",
            "description":"Web- und Frontendtechnologien"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20689,
         "skill":{  
            "id":248,
            "skillId":248,
            "skillName":"Signierung(Code / eMail)",
            "skillGroupName":"Security",
            "description":"Signierung(Code / eMail)"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28500,
         "skill":{  
            "id":284,
            "skillId":284,
            "skillName":"Unixbasierte Betriebsyssteme",
            "skillGroupName":"Sonstiges",
            "description":"Unixbasierte Betriebsyssteme"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20688,
         "skill":{  
            "id":342,
            "skillId":342,
            "skillName":"Security allgemein",
            "skillGroupName":"Security",
            "description":null
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28503,
         "skill":{  
            "id":335,
            "skillId":335,
            "skillName":"IntelliJ",
            "skillGroupName":"Tools",
            "description":null
         },
         "rating":"BASIC",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20691,
         "skill":{  
            "id":253,
            "skillId":253,
            "skillName":"Apache Webserver",
            "skillGroupName":"Servertechnologien",
            "description":"Apache Webserver"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28502,
         "skill":{  
            "id":73,
            "skillId":73,
            "skillName":"Cygwin",
            "skillGroupName":"Tools",
            "description":"Cygwin"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20690,
         "skill":{  
            "id":323,
            "skillId":323,
            "skillName":"TrueCrypt",
            "skillGroupName":"Security",
            "description":null
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28497,
         "skill":{  
            "id":238,
            "skillId":238,
            "skillName":"SQL",
            "skillGroupName":"Sonstiges",
            "description":"SQL"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20693,
         "skill":{  
            "id":260,
            "skillId":260,
            "skillName":"SUN Glassfish",
            "skillGroupName":"Servertechnologien",
            "description":"SUN Glassfish"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28496,
         "skill":{  
            "id":136,
            "skillId":136,
            "skillName":"Lösungspräsentation",
            "skillGroupName":"Sonstiges",
            "description":"Lösungspräsentation"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20692,
         "skill":{  
            "id":258,
            "skillId":258,
            "skillName":"JBoss AS",
            "skillGroupName":"Servertechnologien",
            "description":"JBoss AS"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28499,
         "skill":{  
            "id":241,
            "skillId":241,
            "skillName":"UML- und BPMN-Modellierung",
            "skillGroupName":"Sonstiges",
            "description":"UML- und BPMN-Modellierung"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20695,
         "skill":{  
            "id":66,
            "skillId":66,
            "skillName":"Balsamiq Mockup",
            "skillGroupName":"Tools",
            "description":"Balsamiq Mockup"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":28498,
         "skill":{  
            "id":280,
            "skillId":280,
            "skillName":"Softwarearchitektur",
            "skillGroupName":"Sonstiges",
            "description":"Softwarearchitektur"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1404086400000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":20694,
         "skill":{  
            "id":295,
            "skillId":295,
            "skillName":"Firebug",
            "skillGroupName":"Testing",
            "description":"Firebug"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11106,
         "skill":{  
            "id":47,
            "skillId":47,
            "skillName":"Oracle",
            "skillGroupName":"Datenbanken und Datentechnologien",
            "description":"Oracle"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11107,
         "skill":{  
            "id":45,
            "skillId":45,
            "skillName":"MySQL",
            "skillGroupName":"Datenbanken und Datentechnologien",
            "description":"MySQL"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11104,
         "skill":{  
            "id":149,
            "skillId":149,
            "skillName":"Bash",
            "skillGroupName":"Design und Programmierung",
            "description":"Bash"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11110,
         "skill":{  
            "id":77,
            "skillId":77,
            "skillName":"GIT",
            "skillGroupName":"Tools",
            "description":"GIT"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11111,
         "skill":{  
            "id":80,
            "skillId":80,
            "skillName":"JavaDoc",
            "skillGroupName":"Design und Programmierung",
            "description":"JavaDoc"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11108,
         "skill":{  
            "id":49,
            "skillId":49,
            "skillName":"SQL Server",
            "skillGroupName":"Datenbanken und Datentechnologien",
            "description":"SQL Server"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11109,
         "skill":{  
            "id":76,
            "skillId":76,
            "skillName":"Eclipse",
            "skillGroupName":"Tools",
            "description":"Eclipse"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11114,
         "skill":{  
            "id":88,
            "skillId":88,
            "skillName":"MS Visual Studio",
            "skillGroupName":"Tools",
            "description":"MS Visual Studio"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11115,
         "skill":{  
            "id":315,
            "skillId":315,
            "skillName":"VMWare",
            "skillGroupName":"Netzwerke, Dienste und Monitoring",
            "description":null
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11112,
         "skill":{  
            "id":81,
            "skillId":81,
            "skillName":"JUnit",
            "skillGroupName":"Design und Programmierung",
            "description":"JUnit"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11113,
         "skill":{  
            "id":63,
            "skillId":63,
            "skillName":"Ant",
            "skillGroupName":"Design und Programmierung",
            "description":"Ant"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11119,
         "skill":{  
            "id":162,
            "skillId":162,
            "skillName":"HTML",
            "skillGroupName":"Design und Programmierung",
            "description":"HTML"
         },
         "rating":"EXPERT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"EXPERT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11116,
         "skill":{  
            "id":93,
            "skillId":93,
            "skillName":"OpenOffice",
            "skillGroupName":"Projektorganisationstools",
            "description":"OpenOffice"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11117,
         "skill":{  
            "id":135,
            "skillId":135,
            "skillName":"Kommuniktion mit dem Fachbereich",
            "skillGroupName":"Methoden und Vorgehensmodelle",
            "description":"Kommuniktion mit dem Fachbereich"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11122,
         "skill":{  
            "id":201,
            "skillId":201,
            "skillName":"XML",
            "skillGroupName":"Design und Programmierung",
            "description":"XML"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11121,
         "skill":{  
            "id":112,
            "skillId":112,
            "skillName":"UML",
            "skillGroupName":"Design und Programmierung",
            "description":"UML"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11120,
         "skill":{  
            "id":154,
            "skillId":154,
            "skillName":"CSS",
            "skillGroupName":"Design und Programmierung",
            "description":"CSS"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11093,
         "skill":{  
            "id":226,
            "skillId":226,
            "skillName":"Objektorientierte Methoden und Design",
            "skillGroupName":"Methoden und Vorgehensmodelle",
            "description":"Objektorientierte Methoden und Design"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11095,
         "skill":{  
            "id":39,
            "skillId":39,
            "skillName":"Telekommunikation",
            "skillGroupName":"Branchen",
            "description":"Telekommunikation"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11094,
         "skill":{  
            "id":182,
            "skillId":182,
            "skillName":"PHP",
            "skillGroupName":"Design und Programmierung",
            "description":"PHP"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11097,
         "skill":{  
            "id":291,
            "skillId":291,
            "skillName":"Englisch",
            "skillGroupName":"Sprachen",
            "description":"Englisch"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":null
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11096,
         "skill":{  
            "id":290,
            "skillId":290,
            "skillName":"Deutsch",
            "skillGroupName":"Sprachen",
            "description":"Deutsch"
         },
         "rating":"EXPERT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"EXPERT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11099,
         "skill":{  
            "id":26,
            "skillId":26,
            "skillName":"Windows",
            "skillGroupName":"Betriebssysteme",
            "description":"Windows"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11098,
         "skill":{  
            "id":22,
            "skillId":22,
            "skillName":"Linux",
            "skillGroupName":"Betriebssysteme",
            "description":"Linux"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11101,
         "skill":{  
            "id":42,
            "skillId":42,
            "skillName":"Hibernate",
            "skillGroupName":"Datenbanken und Datentechnologien",
            "description":"Hibernate"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11100,
         "skill":{  
            "id":174,
            "skillId":174,
            "skillName":"Java SE",
            "skillGroupName":"Design und Programmierung",
            "description":"Java SE"
         },
         "rating":"PROFICIENT",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"PROFICIENT",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11103,
         "skill":{  
            "id":197,
            "skillId":197,
            "skillName":"VisualBasic",
            "skillGroupName":"Design und Programmierung",
            "description":"VisualBasic"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":11102,
         "skill":{  
            "id":153,
            "skillId":153,
            "skillName":"C#",
            "skillGroupName":"Design und Programmierung",
            "description":"C#"
         },
         "rating":"BASIC",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"BASIC",
      "modified":false,
      "deleted":false
   },
   {  
      "diffId":null,
      "skillAssignmentInfo":{  
         "id":0,
         "assignmentId":12466,
         "skill":{  
            "id":306,
            "skillId":306,
            "skillName":"Projektmanagement nach PMI",
            "skillGroupName":"Methoden und Vorgehensmodelle",
            "description":"Projektmanagement nach PMI"
         },
         "rating":"ADVANCED",
         "lastUpdatedDate":1399248000000
      },
      "originalSkillValue":"ADVANCED",
      "modified":false,
      "deleted":false
   }
];

var index;
for(index = 0; index < skills.length; index++) {
   var skill = skills[index];
   var name = skill.skillAssignmentInfo.skill.skillName;
   var rating = skill.skillAssignmentInfo.rating;
   name = name.replace(/ /g,"_");

   var ratings = [];
   ratings['THEORETICAL'] = 1;
   ratings['BASIC'] = 2;
   ratings['ADVANCED'] = 3;
   ratings['PROFICIENT'] = 4;
   ratings['EXPERT'] = 5;

   var counter;
   var wordCount = ratings[rating];
   for(counter = 0; counter < wordCount; counter++) {
      console.log(name);
   }
}